### ISSUE TITLE
getting NoClassDefFoundError in samles/AmexCardApplicationOffersClient.java

### ISSUE THREAD

**Issue by ravichoudhary33** [americanexpress/amex-api-java-client-core#1]
Exception in thread "main" java.lang.NoClassDefFoundError: okhttp3/MediaType
	at Experemental.AmexCardApplicationOffersClient.<clinit>(AmexCardApplicationOffersClient.java:23)
Caused by: java.lang.ClassNotFoundException: okhttp3.MediaType
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more

**Comment by dvysotskiy** [comment]
@ravichoudhary33 

Could you please provide additional information about your project? Are you doing Android development by chance? Your configuration files would be very helpful as well. 

Thank you.
